language: python
python: 3.6

cache:
  pip: true

env:
  global:
  - ENCRYPTION_LABEL: "defac9b1fa56"
  - COMMIT_AUTHOR_EMAIL: "nobody@coala.io"

env:
  # This more closely emulates a forked build
  # However the git remote is not correct
  # Only a GH_TOKEN is required.
  - GL_TOKEN="" GCI_TOKEN="" OH_TOKEN=""
  # A proper build with the tokens available
  - AUTH=true

before_install:
  - sed -i '1s/^/coala-bears\n/' requirements.txt
  - npm i -g jshint

script:
  - ./.ci/build.sh
  - rm -rf private/
  - coala --non-interactive -V

after_success:
  - ./.ci/deploy.sh
